language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox -- --ro-functional

notifications:
    email: true
    on_success: never
    on_failure: always
